# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in algorithms.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rake-compiler", "~> 1.2"

gem "benchmark-ips", "~> 2.10"
gem "minitest", "~> 5.0"

gem "rubocop", "~> 1.21"
gem "rubocop-minitest", require: false
gem "rubocop-rake", require: false

gem "debug", ">= 1.0.0"
